import { MediaItem } from './types';

export const MOCK_DATA: MediaItem[] = [
  {
    id: '1',
    type: 'game',
    title: 'Cyberpunk 2077',
    image: 'https://picsum.photos/seed/cyberpunk/400/600',
    genre: ['RPG', 'Action'],
    setting: 'Futuristic',
    themes: ['Politics', 'Transhumanism', 'Crime'],
    tonality: 'Dark',
    targetAudience: 'Adults',
    platform: ['PC', 'PS5', 'Xbox'],
    volume: '50-100 hours',
    rating: 4.5
  },
  {
    id: '2',
    type: 'movie',
    title: 'Blade Runner 2049',
    image: 'https://picsum.photos/seed/bladerunner/400/600',
    genre: ['Sci-Fi', 'Drama'],
    setting: 'Futuristic',
    themes: ['Identity', 'Memory', 'Loneliness'],
    tonality: 'Dark',
    targetAudience: 'Adults',
    volume: '164 min',
    rating: 4.8
  },
  {
    id: '3',
    type: 'book',
    title: 'Neuromancer',
    image: 'https://picsum.photos/seed/neuromancer/400/600',
    genre: ['Cyberpunk', 'Sci-Fi'],
    setting: 'Futuristic',
    themes: ['AI', 'Hacking', 'Corporate Power'],
    tonality: 'Dark',
    targetAudience: 'Adults',
    volume: '271 pages',
    rating: 4.6
  },
  {
    id: '4',
    type: 'game',
    title: 'Hades',
    image: 'https://picsum.photos/seed/hades/400/600',
    genre: ['Roguelike', 'Action'],
    setting: 'Mythological',
    themes: ['Family', 'Freedom', 'Rebellion'],
    tonality: 'Ironic',
    targetAudience: 'Teens/Adults',
    platform: ['PC', 'Switch', 'PS5'],
    volume: '30-60 hours',
    rating: 4.9
  },
  {
    id: '5',
    type: 'book',
    title: 'Circe',
    image: 'https://picsum.photos/seed/circe/400/600',
    genre: ['Fantasy', 'Mythology'],
    setting: 'Mythological',
    themes: ['Isolation', 'Power', 'Transformation'],
    tonality: 'Melancholic',
    targetAudience: 'Adults',
    volume: '393 pages',
    rating: 4.7
  },
  {
    id: '6',
    type: 'movie',
    title: 'The Grand Budapest Hotel',
    image: 'https://picsum.photos/seed/budapest/400/600',
    genre: ['Comedy', 'Adventure'],
    setting: 'Historical (Stylized)',
    themes: ['Friendship', 'Legacy', 'Nostalgia'],
    tonality: 'Ironic',
    targetAudience: 'All',
    volume: '99 min',
    rating: 4.5
  },
  {
    id: '7',
    type: 'game',
    title: 'Elden Ring',
    image: 'https://picsum.photos/seed/eldenring/400/600',
    genre: ['Action RPG', 'Open World'],
    setting: 'Dark Fantasy',
    themes: ['Decay', 'Ambition', 'Godhood'],
    tonality: 'Epic',
    targetAudience: 'Adults',
    platform: ['PC', 'PS5', 'Xbox'],
    volume: '80-150 hours',
    rating: 4.9
  },
  {
    id: '8',
    type: 'book',
    title: 'The Road',
    image: 'https://picsum.photos/seed/theroad/400/600',
    genre: ['Post-apocalyptic'],
    setting: 'Desolate Future',
    themes: ['Survival', 'Fatherhood', 'Despair'],
    tonality: 'Dark',
    targetAudience: 'Adults',
    volume: '287 pages',
    rating: 4.4
  },
  {
    id: '9',
    type: 'movie',
    title: 'Dune: Part Two',
    image: 'https://picsum.photos/seed/dune/400/600',
    genre: ['Sci-Fi', 'Epic'],
    setting: 'Interstellar',
    themes: ['Religion', 'Power', 'Destiny'],
    tonality: 'Epic',
    targetAudience: 'Adults',
    volume: '166 min',
    rating: 4.9
  }
];
